matrix:
  include:
    - os: linux
      language: android
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      android:
        components:
          - tools
          - platform-tools
          - build-tools-25.0.3
          - android-25
          - sys-img-armeabi-v7a-google_apis-25
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-android-support
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
            - fonts-droid
            - libglu1-mesa
            - libglu1-mesa-dev
            - unzip
            - xz-utils
      before_script:
        - wget https://services.gradle.org/distributions/gradle-4.1-all.zip
        - unzip -qq gradle-4.1-all.zip
        - export GRADLE_HOME=$PWD/gradle-4.1
        - export PATH=$GRADLE_HOME/bin:$PATH
        - mkdir flutter
        - cd flutter
        - wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.0.0-stable.tar.xz
        - tar xf flutter_linux_v1.0.0-stable.tar.xz
        - export PATH="$PATH:`pwd`/flutter/bin"
        - cd ..
      script:
        - flutter doctor
cache:
  directories:
    - $HOME/.pub-cache