name: xfocus_mobile
description: xfocus mobile.

dependencies:
  flutter:
    sdk: flutter
  # card_settings: ^1.2.2
  # chewie: ^0.8.0
  # flutter_full_pdf_viewer: ^1.0.1
  # flutter_redux: ^0.5.2
  # onesignal: ^1.0.3
  # pdf: ^1.0.8
  # redux: ^3.0.0
  # rx_widgets: ^2.2.0
  # video_player: ^0.8.0
  after_layout: ^1.0.7
  archive: ^2.0.5
  async_loader: ^0.1.2
  bloc: ^0.7.8
  cached_network_image: ^0.5.1
  camera: ^0.2.6
  carousel_pro: ^0.0.13
  charts_flutter: ^0.5.0
  connectivity: ^0.3.2
  date_range_picker: ^1.0.1
  device_info: ^0.3.0
  dio: ^1.0.13
  firebase_admob: 0.6.1
  firebase_analytics: ^1.0.6
  firebase_auth: ^0.6.6
  firebase_dynamic_links: ^0.1.0+1
  firebase_messaging: ^2.1.0
  fluro: ^1.4.0
  flutter_app_badger: ^1.0.2
  flutter_cache_manager: ^0.2.0+1
  flutter_calendar_carousel: ^1.3.5
  flutter_circular_chart: ^0.1.0
  flutter_colorpicker: ^0.1.0
  flutter_easyrefresh: ^1.0.9
  flutter_local_notifications: ^0.4.3
  flutter_map: ^0.4.0
  flutter_markdown: ^0.2.0
  flutter_picker: ^1.0.5
  flutter_range_slider: ^1.0.1
  flutter_search_bar: ^2.0.7
  flutter_sequence_animation: ^3.0.1
  flutter_slidable: ^0.4.9
  flutter_socket_io: ^0.4.5
  flutter_sparkline: ^0.1.0
  flutter_speed_dial: ^1.0.9
  flutter_spinkit: ^3.1.0
  flutter_staggered_grid_view: ^0.2.5
  flutter_statusbar_manager: ^1.0.2
  flutter_svg: ^0.8.2
  flutter_swiper: ^1.1.4
  flutter_villains: ^1.2.0
  font_awesome_flutter: ^8.2.0
  google_sign_in: ^3.2.4
  http: ^0.12.0
  image_picker: ^0.4.10
  intl: ^0.15.7
  intro_views_flutter: ^2.4.0
  json_annotation: ^2.0.0
  json_serializable: ^2.0.1
  material_design_icons_flutter: ^3.0.3289
  material_search: ^0.2.8
  meta: ^1.1.6
  open_file: ^1.1.1
  open_iconic_flutter: ^0.3.0
  path_provider: ^0.4.1
  percent_indicator: ^1.0.11
  photo_view: ^0.1.2
  qr_flutter: ^1.1.5
  qr_reader: ^0.1.3
  quick_actions: ^0.2.2
  rx_command: ^4.1.0
  rxdart: ^0.20.0
  scoped_model: ^1.0.1
  shared_preferences: ^0.4.3
  simple_auth_flutter: ^2.0.0
  sqflite: any
  sticky_headers: ^0.1.7
  url_launcher: ^4.0.3
  web_socket_channel: ^1.0.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    # svg
    - assets/svg/autodrive.svg
    # png
    - assets/png/logo.png
    - assets/png/logo-50.png
    # json
    - assets/json/cash.json
    - assets/json/inventory.json
    - assets/json/account_receivable.json
    - assets/json/account_payable.json
    - assets/json/sales.json
    - assets/json/counter.json

    # EXAMPLE ASSETS START
    # dribble
    - assets/example/dribble/login.jpg
    - assets/example/dribble/home.jpeg
    - assets/example/dribble/tick.png
    - assets/example/dribble/avatars/avatar-1.jpg
    - assets/example/dribble/avatars/avatar-2.jpg
    - assets/example/dribble/avatars/avatar-3.jpg
    - assets/example/dribble/avatars/avatar-4.jpg
    - assets/example/dribble/avatars/avatar-5.jpg
    - assets/example/dribble/avatars/avatar-6.jpg
    - assets/example/dribble/avatars/default-avatar.jpg
    # bookreader
    - assets/example/bookreader/images/owl.png
    - assets/example/bookreader/images/book1.gif
    - assets/example/bookreader/images/book2.gif
    - assets/example/bookreader/images/book3.gif
    - assets/example/bookreader/images/book4.gif
    # gorgeous_login
    - assets/example/gorgeous_login/img/login_logo.png
    # EXAMPLE ASSETS END
  
  fonts:

    # EXAMPLE FONTS START
    # georgeous_login
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/example/gorgeous_login/fonts/Work_Sans/WorkSans-SemiBold.ttf
    - family: WorkSansBold
      fonts:
        - asset: assets/example/gorgeous_login/fonts/Work_Sans/WorkSans-Bold.ttf
    - family: WorkSansMedium
      fonts:
        - asset: assets/example/gorgeous_login/fonts/Work_Sans/WorkSans-Medium.ttf
    # bookreader
    - family: Fontello
      fonts:
        - asset: assets/example/bookreader/fonts/fontello.ttf
    # EXAMPLE FONTS END
